
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b't\x94\xba=\xdd\xed\xa5\xbc\x8c\x06\xb4\xc0\xcdr\xbcV'
    
_lr_action_items = {'[':([0,2,],[2,2,]),'$end':([1,10,14,],[0,-2,-1,]),'STRING':([2,9,11,],[6,6,6,]),'INTNUM':([2,9,11,],[7,7,7,]),'FLOATNUM':([2,9,11,],[8,8,8,]),';':([3,10,14,],[9,-2,-1,]),']':([4,5,6,7,8,12,13,],[10,-4,-5,-6,-7,14,-3,]),',':([4,5,6,7,8,12,13,],[11,-4,-5,-6,-7,11,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'matrixline':([0,2,],[1,3,]),'valuelist':([2,9,],[4,12,]),'value':([2,9,11,],[5,5,13,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> matrixline","S'",1,None,None,None),
  ('matrixline -> [ matrixline ; valuelist ]','matrixline',5,'p_matrixline','C:\\Users\\user\\Downloads\\tk\\proj\\Mparser.py',128),
  ('matrixline -> [ valuelist ]','matrixline',3,'p_matrixline','C:\\Users\\user\\Downloads\\tk\\proj\\Mparser.py',129),
  ('valuelist -> valuelist , value','valuelist',3,'p_valuelist','C:\\Users\\user\\Downloads\\tk\\proj\\Mparser.py',135),
  ('valuelist -> value','valuelist',1,'p_valuelist','C:\\Users\\user\\Downloads\\tk\\proj\\Mparser.py',136),
  ('value -> STRING','value',1,'p_value','C:\\Users\\user\\Downloads\\tk\\proj\\Mparser.py',143),
  ('value -> INTNUM','value',1,'p_value','C:\\Users\\user\\Downloads\\tk\\proj\\Mparser.py',144),
  ('value -> FLOATNUM','value',1,'p_value','C:\\Users\\user\\Downloads\\tk\\proj\\Mparser.py',145),
]
